### ISSUE TITLE
Classic Conkyrc Suggestion

### ISSUE THREAD

**Issue by akoimeexx** [BunsenLabs/bunsen-conky#3]
Not so much an issue, but a thought; what about adding in a section between System Info and Shortcut keys to show if a network connection is found? I personally add in the following on the crunchbang installations I have:

```
${if_up wlan0}

N E T W O R K
${hr}
IP:$alignr${addr wlan0}
Gateway:$alignr$gw_ip
Current Rate:$alignr${upspeed wlan0}/${downspeed wlan0}
${endif}
```

**Comment by Sector11** [comment]
Because it is machine specific.  It could be wlan0, wlan1, etc.  Others have eth0, eth1, etc. and I believe there is a ppp connection as well.  As little as a year ago I saw that in a conky.

And If I was doing that in a conky it would be like this:

${if_up wlan0}N E T W O R K
${hr}
IP:${alignr}${addr wlan0}
Gateway:${alignr}${gw_ip}
Current Rate:${alignr}${upspeed wlan0} / ${downspeed wlan0}${endif}

That way it uses zero lines in the conky if it is not up.  But that's me.
What you are asking about is best left for the conky support threads or do I'd have a lot more work to cover "all options" - options that I cannot test I might add.

As a side note I have seen people use:  wireless_link_qual  to do what you are doing as well.

**Comment by akoimeexx** [comment]
Fair enough; and I do understand it's hardware-device-name-dependent. The extra spacing is just to match the classic #! conky layout (see 'gap between system and shortcuts'). I wish there was a unified conky variable that just gives you the first 'up' nic details.

**Comment by Sector11** [comment]
Well I can relate to that.  :D
I like the 'unified' connection variable idea, that would be really nice.
