### ISSUE TITLE
menu.xml entry for conky

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-conky#5]
@Sector11 

If you merge the bl-conkyzen scripts, do you want me to make menu.xml entries?

ATM it is:
Settings -> Conky
  ....                                         - Edit .conkyrc
  ....                                         - man page
  ....                                         - Wiki page

It could now include:  
....   - Conky Switcher (ie bl-conkyzen script)
    ....                                      - Reload Conky session (ie default bl-conky-session)

It would be nice to have a pipemenu which gives choices for saved-sessions. This could easily be done if the paths of the saved-sessions files were saved to a config file in $CONKYPATH when they were first created.

**Comment by Sector11** [comment]
Problem with :
.... - Edit .conkyrc
is it edits ~/.conkyrc - unless the symlink changes that - _then go for it!_

Please don't use Conky Switcher (that is what the pipemenu is called.)

Use (just an opinion)
Settings -> Conky
.... - ConkyZen
.... - Reload Session
.... - Edit .conkyrc
.... - man page
.... - Conky Help (x-www-browser http://crunchbang.org/forums/viewtopic.php?pid=371424#p371424)

**NOTE**  - use of ConkyZen and the ConkySwitcher is double jeopardy, since damo's involvement ConkyZen is the better choice.  (my opinion)

**Comment by capn-damo** [comment]
For a menu label I don't think "ConkyZen" is a good description - it describes the script, not the process - it would be meaningless to a new user. 
What the user is wanting is a chooser/switcher for his conkys. A pipemenu or script can be called anything you like, but the menu label is what a user sees. "Conky Chooser"?

Maybe change "Edit .conkyrc" to "Edit default conky"?

And are man/conky help links necessary here as well? They are in all the Help menu

**Comment by Sector11** [comment]
OK - I'm not fussy ... make it look good.  :dart: 

Settings -> Conky
.... - Conky Chooser
.... - Reload Session
.... - Edit .conkyrc or Edit default Conky

if the symlink works - does it make a difference?  Other than Edit .conkyrc is about the same width as the rest.

Six to one half-a-dozen to the other.

I was looking at the "Help" section ... those maybe should be changed to:
.... - man page
.... - Conky Help (x-www-browser http://crunchbang.org/forums/viewtopic.php?pid=371424#p371424)

That last one vs the Wiki Page which is discontinued.
