### ISSUE TITLE
Move BL-Default.conkyrc to bunsen-configs?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-conky#9]
I was thinking, some users might not install bunsen-conky but we still should have a default conky in the standard install. 

Would it be OK to move BL-Default.conkyrc to the **bunsen-configs** package? The install path would still be the same so it would fit in with the other **bunsen-conky** files when they get installed. 

Also, the symlink from ~/.conkyrc to ~/.config/conky/BL-Default.conkyrc gets put in by bunsen-configs so it would be good to guarantee the file is there so the link isn't broken.

**Comment by Sector11** [comment]
Sounds like a good solid plan.  HOWEVER.  I see someone trying to "edit" ~/.conkyrc and then because of the symlink end up editing BL-Default.conkyrc.

Maybe if during the install process it does a copy:
`cp $HOME/.config/conky/BL-default.conkyrc ~/.conkyrc`
and have the Conky Chooser include ~/.conkyrc in the list as well.

Now people can run a single "conky" command and it starts what conky considers the norm AND the Conky Chooser still works.

Just my 2¢

**Comment by johnraff** [comment]
Would it be a problem if a user edited BL-Default.conkyrc? Are they not supposed to edit those files?
...
I think the latest version of conky chooser picks up a conky running from ~/.conkyrc, so it would be possible to have a default file there instead of a symlink. But if we copy $HOME/.config/conky/BL-default.conkyrc to  ~/.conkyrc then now we've got _two_ default conky config files. Which one is the user supposed to edit?
...
I guess after all we could go back to having bunsen-configs installing ~/.conkyrc, bunsen-conky install  ~/.config/conky/*, and forget about symlinks. (And put the default conky in ~/.conkyrc) As long as Conky Chooser can handle the situation it might be OK?

**Comment by Sector11** [comment]
`Would it be a problem if a user edited BL-Default.conkyrc?`
No it's a users option the same as editing the #! default conky at ~/.conkyrc

Once installed these files should never be over written by "updates", the #! ~/.conkyrc was installed with the system and from that point on - the users option to keep it or edit it.

`Are they not supposed to edit those files?`
That's a users choice.  Conkys are highly personal and once a user adds lm-sensors, hddtemp, vnstats to them (and a lot more) they become "machine" specific and personalized.

For example two possible versions of what I might do with the default conky:

http://postimg.org/image/usy6kdkg9/

At first glance they look the same, they aren't the one on the right has a few extra things added.

And that's the thing with conkys.  People that like tweaking or creating them might very well edit the conkys in ~/.config/conky - in fact my OLD version if the Zenity script had another version to do just that.  I still use that setup today for my current running conkys in #! Wheezy.  Because when I want to edit:
- my weather conky for example it opens the conky and the bash script that gets the weather
- my S11-Rem-Cal.conky it opens 4 files related to that conky in my editor.

http://postimg.org/image/46lpveg95/

So the idea of having the default Bunsen conky at ~/.conkyrc fall right in line with the idea of how conky works.  Then having it at ~/.config/conky by a different name declaring it the Bunsen default (in the name) means it's almost like a backup.

**Comment by johnraff** [comment]
Almost like a backup - great idea which hadn't occurred to me. 

###### OK let's drop the symlink and just put a copy of BL-Default.conkyrc at ~/.conkyrc. That file can be installed by bunsen-configs and everything in ~/.config/conky by bunsen-conky. Does that sound good?

Of course all the "skel" stuff only gets installed into the user's HOME once - on their first login - after that they can tweak and edit as they like. It's in their own domain after all. Any upgrades of bunsen-configs which might change the contents of 'skel' will have no effect on the user's own files, unless they deliberately pull something in from 'skel'.
...which brings me to another question. What if a user installs bunsen-conky _after_ their first setup? They'll never get the conky stuff because it will stay in 'skel'. I think that should be a new issue, so I'll start one.

BTW 'skel' might get moved soon from /etc/ to /usr/share/bunsen/bunsen-configs but that won't change anything about how all this works.

**Comment by Sector11** [comment]
YES!  Perfect.

If you put a copy of the Default conky in as ~/.conkyrc that install has the default conky.

2 days later bunsen-conky is installed, why would it stay in /skel?  It's a fresh install it should go to it location in the $HOME folder.
